# CASA0007 
## Practical 4: Linear Algebra</h1>
<div style="float:right"><img width="100" src="https://github.com/jreades/i2p/raw/master/img/casa_logo.jpg" /></div>

## Welcome!

In this practical, we will apply some techniques from linear algebra. 

- Systems of equations 
- Matrix operations 

In [1]:
# import relevant packages

import numpy as np
import scipy.stats as sps
import pandas as pd
import matplotlib.pyplot as plt

# import 3d plotting tools
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch

A factory produces three products:

- $x$ — handlebars  
- $y$ — brakes  
- $z$ — wheels  

From **each piece of aluminium** they can produce: 4 of $x$, 3 of $y$, and 8 of $z$.  
From **each unit of rubber** they can produce: 1 of $x$, 100 of $y$, and 9 of $z$.  
From **each unit of paint** they can produce: $ of $x$, 0 of $y$, and 2 of $z$.  

Suppose the factory has:  
- $A$ pieces of aluminium,  
- $R$ units of rubber,  
- $P$ units of paint.  

How many of each product $x, y, z$ can they produce?  

## Linear equations  

We can express the resource constraints as a system of equations:  

```{=tex}
4x + 3y + 8z &= A, 
x + 100y + 9z &= R, 
9x + 0y + 2z &= P.

## Matrix form

This can be written compactly as:

```{=tex}
\begin{bmatrix}
4 & 3 & 8 \\
1 & 100 & 9 \\
9 & 0 & 2
\end{bmatrix}§

\begin{pmatrix}x\\y\\z\end{pmatrix}
=
\begin{pmatrix}A\\R\\P\end{pmatrix}.
```


That is, 
```{=tex}
Mx =b 
```

In [2]:
# written in python as: 

# Coefficient matrix (resources -> products)
M = np.array([[4, 3, 8],
              [1, 100, 9],
              [9, 0, 2]], dtype=float)

# Resource availability
b = np.array([100.0, 300.0, 150.0])  # [A, R, P]

We can use in-built functions in Python to solve the system of linear equations. 

First lets check the determinant of A is non-zero. 

In [3]:
# Calculate the determinant of M
det_M = np.linalg.det(M)
print(det_M)

-6163.000000000011


The det(A) is non-zero - hence we know A is invertibe. 

In [4]:
# The inverse of a matrix A is denoted A^-1 and has the property that A * A^-1 = I, where I is the identity matrix.
# Invert A 

M_inv = np.linalg.inv(M)
print(M_inv)

[[-0.03245173  0.00097355  0.12542593]
 [-0.01281843  0.01038455  0.00454324]
 [ 0.14603278 -0.00438098 -0.06441668]]


Check that AA^{-1}= I

In [5]:
# Multiply A by its inverse to get the identity matrix
MM_inv = np.dot(M, M_inv)
print(MM_inv)

[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [-1.94289029e-16  1.00000000e+00 -2.77555756e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


It's the identity matrix!

Now we can solve to find x!

In [6]:
# do A^-1 * y to get x
x = np.dot(M_inv, b)
print(x)

[15.86078209  2.51500892  3.62648061]


Alternatively we can solve the equations using `numpy`s linear algebra solver. 

In [7]:
## Solve the equations using numpy's linear algebra solver
x = np.linalg.solve(M, b)
print(x)

[15.86078209  2.51500892  3.62648061]


Plot the equations in 3D space - where the 3 planes intersect is our solution!

In [11]:
import numpy as np
import plotly.graph_objects as go

# Coefficients and resources
A, R, P = 100, 300, 150

# Define grid
x = np.linspace(0, 30, 50)
y = np.linspace(0, 30, 50)
X, Y = np.meshgrid(x, y)

# Constraint surfaces
Z1 = (A - 4*X - 3*Y) / 8
Z2 = (R - X - 100*Y) / 9
Z3 = (P - 9*X) / 2

# Solve system
M = np.array([[4, 3, 8],
              [1,100, 9],
              [9, 0, 2]], dtype=float)
b = np.array([A, R, P], dtype=float)
solution = np.linalg.solve(M, b)

# Create interactive 3D plot
fig = go.Figure()

fig.add_surface(x=x, y=y, z=Z1, opacity=0.5, colorscale="Blues", name="Aluminium")
fig.add_surface(x=x, y=y, z=Z2, opacity=0.5, colorscale="Oranges", name="Rubber")
fig.add_surface(x=x, y=y, z=Z3, opacity=0.5, colorscale="Greens", name="Paint")

# Add solution point
fig.add_trace(go.Scatter3d(x=[solution[0]], y=[solution[1]], z=[solution[2]],
                           mode="markers", marker=dict(size=6, color="red"),
                           name="Solution"))

fig.update_layout(
    scene=dict(
        xaxis_title="Handlebars (x)",
        yaxis_title="Brakes (y)",
        zaxis_title="Wheels (z)"
    ),
    title="Interactive 3D Production Constraints"
)

fig.show()


## Credits
### Contributors:
The following individuals have contributed to these teaching materials: [Bea Taylor](https://github.com/Bea-Taylor)

### License
These teaching materials are licensed under a mix of The MIT License and the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 license.

### Acknowledgements
NA

### Dependencies
This notebook depends on the following libraries: pandas, matplotlib, numpy, scipy